version: '3.8'

networks:
    dev_network:
        name: dev_network
        driver: bridge

services:
    db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./bienes_raices.sql:/docker-entrypoint-initdb.d/bienes_raices.sql
        networks:
            - dev_network

    web:
        build:
            context: .
            dockerfile: dockerfile
        image: django_full_stack:v1.0
        container_name: django_web
        command: sh -c "npm run dev & python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/app/
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - dev_network

volumes:
    postgres_data:
