# Usar una imagen base de Python 3.12
FROM python:3.12.7-alpine3.20

# Establecer el directorio de trabajo
WORKDIR /usr/app/

# Instalar dependencias de Python
RUN apk update && \
    apk add --no-cache gcc musl-dev libffi-dev postgresql-dev && \
    pip install --upgrade pip

# Copiar y instalar las dependencias de Python
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación
COPY ./ ./
