# Generated by Django 5.1.1 on 2024-10-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='fecha_actualiacion',
            new_name='fecha_actualizacion',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen'),
        ),
    ]
