# Generated by Django 5.1.1 on 2024-10-02 08:08

import propiedades.context_processors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_alter_propiedad_imagen_alter_propiedad_wc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(upload_to=propiedades.context_processors.get_unique_filename, verbose_name='Imagen'),
        ),
    ]
